name: Deploy project # Name of the workflow
on: [push, workflow_dispatch] # Event that triggers the workflow
jobs: # Jobs that run in the workflow
  test: # Name of the job
    runs-on: ubuntu-latest # Operating system to run the job
    steps: # Steps that run in the job
      - name: Checkout code # Name of the step
        uses: actions/checkout@v3 # Action to checkout the code
      - name: Install nodeJS
        uses: actions/setup-node@v3
        with:
          node-version: "18"
      - name: Install dependencies
        run: npm ci # Command to run in the step
      - name: Run tests # Name of the step
        run: npm test # Command to run in the step
  deploy: # Name of the job
    runs-on: ubuntu-latest # Operating system to run the job
    needs: test # Job that must complete before this job
    steps: # Steps that run in the job
      - name: Checkout code # Name of the step
        uses: actions/checkout@v3 # Action to checkout the code
      - name: Install nodeJS
        uses: actions/setup-node@v3
        with:
          node-version: "18"
      - name: Install dependencies
        run: npm ci # Command to run in the step
      - name: Build project
        run: npm run build
      - name: Deploy project # Name of the step
        run: echo "Deploying.. " # Command to run in the step
